const normalizeDocumentEntry = (entry) => ({
	fileUrl: entry?.fileUrl || '',
	publicId: entry?.publicId || '',
	status: entry?.status || 'missing',
	expiry: entry?.expiry || '',
})

export const getRequiredDocumentsDefaults = () => ({
	w9Form: { fileUrl: '', publicId: '', status: 'missing', expiry: '' },
	articleOfIncorporation: { fileUrl: '', publicId: '', status: 'missing', expiry: '' },
	einCertificate: { fileUrl: '', publicId: '', status: 'missing', expiry: '' },
	cityPermit: { fileUrl: '', publicId: '', status: 'missing', expiry: '' },
	voidCheck: { fileUrl: '', publicId: '', status: 'missing', expiry: '' },
	profilePicture: { fileUrl: '', publicId: '', status: 'missing', expiry: '' },
	licensePicture: { fileUrl: '', publicId: '', status: 'missing', expiry: '' },
	limoLicenseDecal: { fileUrl: '', publicId: '', status: 'missing', expiry: '' },
	liabilityInsurance: { fileUrl: '', publicId: '', status: 'missing', expiry: '' },
	vehicleRegistration: { fileUrl: '', publicId: '', status: 'missing', expiry: '' },
	cityPermittedSticker: { fileUrl: '', publicId: '', status: 'missing', expiry: '' },
	licensePlatePhoto: { fileUrl: '', publicId: '', status: 'missing', expiry: '' },
	airportPermit: { fileUrl: '', publicId: '', status: 'missing', expiry: '' },
})

export const normalizeRequiredDocuments = (data) => {
	const docs = data?.requiredDocuments || {}
	return {
		w9Form: normalizeDocumentEntry({ fileUrl: docs.w9FormUrl, status: docs.w9FormStatus, expiry: docs.w9FormExpiry }),
		articleOfIncorporation: normalizeDocumentEntry({ fileUrl: docs.articleOfIncorporationUrl, status: docs.articleOfIncorporationStatus, expiry: docs.articleOfIncorporationExpiry }),
		einCertificate: normalizeDocumentEntry({ fileUrl: docs.einCertificateUrl, status: docs.einCertificateStatus, expiry: docs.einCertificateExpiry }),
		cityPermit: normalizeDocumentEntry({ fileUrl: docs.cityPermitUrl, status: docs.cityPermitStatus, expiry: docs.cityPermitExpiry }),
		voidCheck: normalizeDocumentEntry({ fileUrl: docs.voidCheckUrl, status: docs.voidCheckStatus, expiry: docs.voidCheckExpiry }),
		profilePicture: normalizeDocumentEntry({ fileUrl: docs.profilePictureUrl, status: docs.profilePictureStatus, expiry: docs.profilePictureExpiry }),
		licensePicture: normalizeDocumentEntry({ fileUrl: docs.licensePictureUrl, status: docs.licensePictureStatus, expiry: docs.licensePictureExpiry }),
		limoLicenseDecal: normalizeDocumentEntry({ fileUrl: docs.limoLicenseDecalUrl, status: docs.limoLicenseDecalStatus, expiry: docs.limoLicenseDecalExpiry }),
		liabilityInsurance: normalizeDocumentEntry({ fileUrl: docs.liabilityInsuranceUrl, status: docs.liabilityInsuranceStatus, expiry: docs.liabilityInsuranceExpiry }),
		vehicleRegistration: normalizeDocumentEntry({ fileUrl: docs.vehicleRegistrationUrl, status: docs.vehicleRegistrationStatus, expiry: docs.vehicleRegistrationExpiry }),
		cityPermittedSticker: normalizeDocumentEntry({ fileUrl: docs.cityPermittedStickerUrl, status: docs.cityPermittedStickerStatus, expiry: docs.cityPermittedStickerExpiry }),
		licensePlatePhoto: normalizeDocumentEntry({ fileUrl: docs.licensePlatePhotoUrl, status: docs.licensePlatePhotoStatus, expiry: docs.licensePlatePhotoExpiry }),
		airportPermit: normalizeDocumentEntry({ fileUrl: docs.airportPermitUrl, status: docs.airportPermitStatus, expiry: docs.airportPermitExpiry }),
	}
}

export const buildRequiredDocumentsPayload = (docs) => ({
	w9FormUrl: docs?.w9Form?.fileUrl || null,
	w9FormStatus: docs?.w9Form?.fileUrl ? 'uploaded' : 'missing',
	w9FormExpiry: docs?.w9Form?.expiry || null,
	articleOfIncorporationUrl: docs?.articleOfIncorporation?.fileUrl || null,
	articleOfIncorporationStatus: docs?.articleOfIncorporation?.fileUrl ? 'uploaded' : 'missing',
	articleOfIncorporationExpiry: docs?.articleOfIncorporation?.expiry || null,
	einCertificateUrl: docs?.einCertificate?.fileUrl || null,
	einCertificateStatus: docs?.einCertificate?.fileUrl ? 'uploaded' : 'missing',
	einCertificateExpiry: docs?.einCertificate?.expiry || null,
	cityPermitUrl: docs?.cityPermit?.fileUrl || null,
	cityPermitStatus: docs?.cityPermit?.fileUrl ? 'uploaded' : 'missing',
	cityPermitExpiry: docs?.cityPermit?.expiry || null,
	voidCheckUrl: docs?.voidCheck?.fileUrl || null,
	voidCheckStatus: docs?.voidCheck?.fileUrl ? 'uploaded' : 'missing',
	voidCheckExpiry: docs?.voidCheck?.expiry || null,
	profilePictureUrl: docs?.profilePicture?.fileUrl || null,
	profilePictureStatus: docs?.profilePicture?.fileUrl ? 'uploaded' : 'missing',
	profilePictureExpiry: docs?.profilePicture?.expiry || null,
	licensePictureUrl: docs?.licensePicture?.fileUrl || null,
	licensePictureStatus: docs?.licensePicture?.fileUrl ? 'uploaded' : 'missing',
	licensePictureExpiry: docs?.licensePicture?.expiry || null,
	limoLicenseDecalUrl: docs?.limoLicenseDecal?.fileUrl || null,
	limoLicenseDecalStatus: docs?.limoLicenseDecal?.fileUrl ? 'uploaded' : 'missing',
	limoLicenseDecalExpiry: docs?.limoLicenseDecal?.expiry || null,
	liabilityInsuranceUrl: docs?.liabilityInsurance?.fileUrl || null,
	liabilityInsuranceStatus: docs?.liabilityInsurance?.fileUrl ? 'uploaded' : 'missing',
	liabilityInsuranceExpiry: docs?.liabilityInsurance?.expiry || null,
	vehicleRegistrationUrl: docs?.vehicleRegistration?.fileUrl || null,
	vehicleRegistrationStatus: docs?.vehicleRegistration?.fileUrl ? 'uploaded' : 'missing',
	vehicleRegistrationExpiry: docs?.vehicleRegistration?.expiry || null,
	cityPermittedStickerUrl: docs?.cityPermittedSticker?.fileUrl || null,
	cityPermittedStickerStatus: docs?.cityPermittedSticker?.fileUrl ? 'uploaded' : 'missing',
	cityPermittedStickerExpiry: docs?.cityPermittedSticker?.expiry || null,
	licensePlatePhotoUrl: docs?.licensePlatePhoto?.fileUrl || null,
	licensePlatePhotoStatus: docs?.licensePlatePhoto?.fileUrl ? 'uploaded' : 'missing',
	licensePlatePhotoExpiry: docs?.licensePlatePhoto?.expiry || null,
	airportPermitUrl: docs?.airportPermit?.fileUrl || null,
	airportPermitStatus: docs?.airportPermit?.fileUrl ? 'uploaded' : 'missing',
	airportPermitExpiry: docs?.airportPermit?.expiry || null,
})
